---
version: '2'
services:
  website:
    image: php:apache
    container_name: website
    ports:
      - 80:80
    volumes:
      - ./website:/var/www/html
    depends_on:
      - student_list
    environment:
      - USERNAME="${API_USERNAME}"
      - PASSWORD="${API_PASSWORD}"

  student_list:
    image: "${REGISTRY_URL}/team2/student_list"
    container_name: student_list
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json  
...
