---
- name: Install docker on a Centos 7 machine
  hosts: client
  tasks:
  - name: Install Docker
    yum: 
      name=docker-engine 
      state=latest
    become: yes

  - name: Start and enable the Docker daemon
    service: 
      name=docker 
      state=started 
      enabled=yes
    become: yes

  - name: Add remote user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
    become: yes

  - name: Start and enable the Docker daemon
    service: 
      name=docker 
      state=started 
      enabled=yes
    become: yes

  - name: Install Docker Module for Python
    pip:
      name: docker
      executable: pip3
    vars:
      ansible_python_interpreter: /usr/bin/python3
...
