---
- name: "student_list installation"
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create api containers
      docker_container:
        name: "portainer_agent"
        image: "portainer/agent"
        pull: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        ports:
          - 9001:9001
        restart_policy: "unless-stopped"
...
