---
- name: Install docker on Oracle Linux
  hosts: prod
  tasks:
  - name: Install Docker
    yum:
      name=docker-engine
      state=latest
    become: true

  - name: Install pip3 on remote machines
    shell: curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
    become: true

  - name: "Install libselinux-python3"   # required for some ansible module
    yum:
      name: libselinux-python3
      state: present
      update_cache: true
    become: true

  - name: Start and enable the Docker daemon
    service:
      name=docker
      state=started
      enabled=true
    become: true

  - name: Add remote user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: true
    become: true

  - name: Install Docker Module for Python
    pip:
      name: docker
      executable: pip3
    vars:
      ansible_python_interpreter: /usr/bin/python3
...
