---
- name: Install docker on Oracle Linux
  hosts: prod
  tasks:
  - name: Install Docker
    yum: 
      name=docker-engine 
      state=latest
    become: yes

  - name: Install pip3 on remote machines
    shell: curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
    become: yes

  - name: "Install libselinux-python3" # required for some ansible module to work
    yum:
      name: libselinux-python3
      state: present
      update_cache: yes
    become: yes

  - name: Start and enable the Docker daemon
    service: 
      name=docker 
      state=started 
      enabled=yes
    become: yes

  - name: Add remote user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
    become: yes

  - name: Install Docker Module for Python
    pip:
      name: docker
      executable: pip3
    vars:
      ansible_python_interpreter: /usr/bin/python3
...
