--- 
- name: "student_list installation"
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Remove containers api
      docker_container:
        name: "student_list"
        image: "{{ registry_url }}/team2/student_list"
        state: absent
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Remove containers website
      docker_container:
        name: "website"
        image: "php:apache"
        state: absent

#    - name: "Allow insecure registry"  ## not required anymore since our registry now work on https
#      copy:
#        content: { "insecure-registries":["<ip>:<port>"] }
#        dest: /etc/docker/daemon.json
#      become: yes
#
#    - name: Start and enable the Docker daemon
#      service:
#        name=docker
#        state=restarted
#        enabled=yes
#      become: yes

    - name: Log into private registry and force re-authorization
      community.docker.docker_login:
        registry_url: "{{ registry_url }}"
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
        reauthorize: yes

    - name: Generate student_age.json
      template:
        src: ../simple_api/student_age.json
        dest: ~/student_age.json

    - name: "Create a network"
      docker_network:
        name: "student_list"

    - name: Create api containers
      docker_container:
        name: "student_list"
        image: "{{ registry_url }}/team2/student_list"
        pull: yes
        volumes:
          - ~/student_age.json:/data/student_age.json
        networks:
          - name: "student_list"

    - name: Generate website
      template:
        src: ../website/index.php
        dest: ~/index.php

    - name: Create website containers
      docker_container:
        name: "website"
        image: "php:apache"
        ports: 80:80
        pull: yes
        volumes:
          - ~/index.php:/var/www/html/index.php
        networks:
          - name: "student_list"
        env:
          USERNAME: "toto"
          PASSWORD: "python"
...
