---
- name: "student_list installation"
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Log into private registry and force re-authorization
      community.docker.docker_login:
        registry_url: "{{ registry_url }}"
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
        reauthorize: true

    - name: Generate student_age.json
      template:
        src: ../simple_api/student_age.json
        dest: ~/student_age.json
        mode: 0644

    - name: "Create a network"
      docker_network:
        name: "student_list"

    - name: Create api containers
      docker_container:
        name: "student_list"
        image: "{{ registry_url }}/team2/student_list"
        pull: true
        recreate: true
        volumes:
          - ~/student_age.json:/data/student_age.json
        networks:
          - name: "student_list"
        healthcheck:
          test: curl -fs http://localhost:5000/pozos/api/v1.0/get_student_ages || exit 1
          timeout: 30s
          interval: 1m
          retries: 3

    - name: Generate website
      template:
        src: ../website/index.php
        dest: ~/index.php
        mode: 0644

    - name: Create website containers
      docker_container:
        name: "website"
        image: "php:apache"
        ports: 80:80
        pull: true
        recreate: true
        volumes:
          - ~/index.php:/var/www/html/index.php
        networks:
          - name: "student_list"
        env:
          USERNAME: "{{ api_username }}"
          PASSWORD: "{{ api_password }}"
        healthcheck:
          test: curl -fs http://localhost || exit 1
          timeout: 30s
          interval: 1m
          retries: 3
          
    - name: Prune everything to save space
      community.docker.docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
...
